apiVersion: v1
kind: ReplicaSet
metadata:
name: httpserver
spec:
replicas: 3
selector:
  matchLabels:
    app: httpserver
template:
  metadata:
    labels:
    app: httpserver
  spec:
    containers:
    - name: httpserver
      image: wentingada/httpserver:0.0